version: "3.8"

services:
  app:
    build: .
    container_name: todo_list
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres_educt:5432/todo_list
    depends_on:
      - postgres_educt

  postgres_educt:
    image: postgres:16-alpine
    container_name: postgres_todo_list
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_list
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
